"use client";

import "./globals.css";
import Head from 'next/head';
import { useState } from 'react';

export default function RootLayout({ children }) {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
    document.body.classList.toggle('dark-mode');
  };

  return (
    <html lang="en">
      <Head>
        <title>ganesh-site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
        {/* Removed script related to chatbot */}
      </Head>
      <body className={darkMode ? 'dark-mode' : ''}>
        <header>
          <nav>
            <div 
              className={`toggle-container ${darkMode ? 'dark' : ''}`} 
              onClick={toggleDarkMode}
              id="darkModeToggle"
            >
              <span className="emoji sun">🌞</span>
              <div className="toggle-button"></div>
              <span className="emoji moon">🌜</span>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
