"use client";

import "./globals.css";
import Head from "next/head";
import { useState, useEffect } from "react";

export default function RootLayout({ children }) {
  const [darkMode, setDarkMode] = useState(false);

  // Initialize theme
  useEffect(() => {
    const savedTheme = localStorage.getItem("theme");
    const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

    // Priority order: 1. Saved theme 2. System preference
    if (savedTheme === "dark" || (!savedTheme && systemDark)) {
      setDarkMode(true);
      document.body.classList.add("dark-mode");
    }

    // Inject Botpress Chatbot Script
    const script1 = document.createElement("script");
    script1.src = "https://cdn.botpress.cloud/webchat/v2.3/inject.js";
    script1.async = true;
    document.body.appendChild(script1);

    const script2 = document.createElement("script");
    script2.src = "https://files.bpcontent.cloud/2025/04/03/07/20250403074736-K4DAODK3.js";
    script2.async = true;
    document.body.appendChild(script2);

    return () => {
      document.body.removeChild(script1);
      document.body.removeChild(script2);
    };
  }, []);

  const toggleDarkMode = () => {
    const newDarkMode = !darkMode;
    setDarkMode(newDarkMode);
    document.body.classList.toggle("dark-mode");
    localStorage.setItem("theme", newDarkMode ? "dark" : "light");
  };

  return (
    <html lang="en">
      <Head>
        <title>ganesh-site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Space+Grotesk:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <header>
          <nav>
            <div
              className={`toggle-container ${darkMode ? "dark" : ""}`}
              onClick={toggleDarkMode}
            >
              <span className="emoji sun">🌞</span>
              <div className="toggle-button"></div>
              <span className="emoji moon">🌜</span>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
